### ISSUE TITLE
Update oAuth instructions to include 2 extra scopes

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-azure-devops#137]
The oAuth instructions list 2 scopes
`vso.code_full` and `vso.work_full` 
as of 3.x.x - `vso.build_execute` and  `vso.release_manage` are also required. setup should be updated.

**Comment by avas27JTG** [comment]
@DHaussermann The oAuth instructions for `3.x.x` is already updated in the README present in phase-3 branch [here](https://github.com/mattermost/mattermost-plugin-azure-devops/blob/epic_phase_3/docs/oauth_setup.md).

Please verify it and let us know if we can close this issue.

**Comment by DHaussermann** [comment]
Thanks @avas27JTG 
Confirmed resolved in the `epic_phase_3` branch.

Closing.
