### ISSUE TITLE
Consider matching Azure DevOps icons for some subcommands 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-azure-devops#155]
The Azure DevOps plugin covers 3 different product areas but all as one single plugin. As such, it would be more intuitive to learn and use the Azure DevOps plugin if the auto-complete icons for `Pipelines`, `Repos` and `Boards` matched the in-product icons.

Replace the icon for the 3 subcommands below with the icons used in the product.
![image](https://user-images.githubusercontent.com/35588783/231583273-78c97af2-715c-4b76-bbbc-660d7bad4b45.png)

![image](https://user-images.githubusercontent.com/35588783/231583345-e5275443-d0ee-4088-8143-7bf38bd6acd2.png)

**I think** it is possible to have unique icons defined. As per dev, the data structure does support this.

**Comment by avas27JTG** [comment]
@DHaussermann As we understand it we think you are asking to change the icon for subcommands `board, repos, and pipelines` with their respective product icons in the below slash command list
![image](https://user-images.githubusercontent.com/72438220/232497337-11812583-40f5-44f2-9673-81ff9b9d8865.png)

But we could not make this change, as for now there isn't support for that to do through the plugin, I tried reaching out to devs on the community also you can refer to this conversation for more details https://community.mattermost.com/core/pl/467mf9e1wfruxdqwo47frisbuc

Please let us know if we can close this issue or if there is anything else to do here.

**Comment by DHaussermann** [comment]
Ah I see @avas27JTG. Yes this is what I was wondering about. I was under the impression it may be possible. Thanks for checking.

**Comment by DHaussermann** [comment]
This cannot be implemented. The plugin framework does not allow for customizing the icons of individual subcommands. 

Closing.
