### ISSUE TITLE
Task preview is returning the wrong azure task

### ISSUE THREAD

**Issue by viniciusss** [mattermost/mattermost-plugin-azure-devops#158]
## Case
When i send the message with a task with a 0 in the midle, Azure is returning the wrong task:

![image](https://github.com/mattermost/mattermost-plugin-azure-devops/assets/1016025/4a5ea9f6-8766-40f2-8cd6-51ea898783f0)

## Installed Plugin Version
Azure DevOps (mattermost-plugin-azure-devops - 3.2.0)

## Mattermost Server Info

Mattermost Version: 7.10.2
Database Schema Version: 108
Database: mysql

**Comment by viniciusss** [comment]
hey @mickmister, could you release a new version with the bugfix merged?

**Comment by mickmister** [comment]
@viniciusss Yes this is in our release queue. Thanks for following up here :+1:

Fixed with https://github.com/mattermost/mattermost-plugin-azure-devops/pull/160
